# Generated by Django 5.2.8 on 2025-11-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_cvdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdownload',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cvdownload',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
