# Generated by Django 5.2.8 on 2025-11-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_cvdownload_ip_address_cvdownload_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdownload',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvdownload',
            name='referrer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
