# Generated by Django 5.2.8 on 2025-11-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_cvdownload_os_cvdownload_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdownload',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
