# Generated by Django 5.2.8 on 2025-12-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_skillcategory_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Julius Nartey', max_length=100)),
                ('bio', models.TextField(default="I'm a software engineer experienced in building scalable backend systems, developer-friendly APIs, and modern frontends. I enjoy solving hard problems and mentoring engineers.")),
                ('location', models.CharField(default='Accra, Ghana', max_length=100)),
                ('availability', models.CharField(default='Open to work / contract', max_length=100)),
                ('email', models.EmailField(default='julius.nartey.71@gmail.com', max_length=254)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
            },
        ),
    ]
