# Generated by Django 5.2.8 on 2025-12-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_aboutme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'About Mee', 'verbose_name_plural': 'About Me'},
        ),
    ]
