# Generated by Django 5.2.8 on 2026-01-19 08:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_project_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_u',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text'),
        ),
    ]
