# Generated by Django 5.2.8 on 2026-01-19 08:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_project_description_u'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description_u',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description'),
        ),
    ]
