# Generated by Django 5.2.8 on 2026-01-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_remove_project_description_u_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='learnings',
        ),
        migrations.RemoveField(
            model_name='project',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='project',
            name='solution',
        ),
    ]
