# Generated by Django 5.2.8 on 2026-01-20 14:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_project_challenges_remove_project_learnings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfeature',
            name='name',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Feature'),
        ),
    ]
